pipeline:
  publish-api-docker:
    image: plugins/docker
    settings:
      repo: romaspirin/tnt-cow
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
